version: "3.7"

services:

  postgres-db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    env_file:
      - ./env/postgres-db.env
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
      - ./conf/postgres-db/create-initial-databases.sh:/docker-entrypoint-initdb.d/create-initial-databases.sh
    networks:
      - asgard_net

  heimdall:
    image: heimdall
    container_name: heimdall
    build:
      context: ./heimdall
    restart: always
    env_file:
      - ./env/heimdall.env
    ports:
      - 8080:8080
      - 8443:8443
      - 9000:9000
      # - 7600-7800:7600-7800
      # - 57600-57800:57600-57800
    networks:
      - asgard_pub
      - asgard_net
    depends_on:
      - postgres-db

  odin:
    image: odin
    container_name: odin
    command: ["--reload"]
    build:
      context: ./odin
    restart: always
    env_file:
      - ./env/odin.env
    networks:
      - asgard_pub
      - asgard_net
    depends_on:
      - heimdall
    volumes:
      - ./odin:/app
    ports:
      - 80:80
   

volumes:
  postgres_db_data: {}


networks:
  default:
    driver: bridge
  asgard_pub:
    # open network access, please use only when necessary
    internal: false
  asgard_net:
    # private, inter-system channel
    internal: true



# postgres -> db
# keycloak -> heimdall
# kong -> bifrost
# redis
# pushpin -> harbinger
# airbyte -> Huginn
# airflow -> Muninn
# postgres for pipelines -> mimir
