version: "3.7"

services:

  postgres-db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    env_file:
      - ./.env/postgres-db.env
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
      - ./.conf/postgres-db/create-initial-databases.sh:/docker-entrypoint-initdb.d/create-initial-databases.sh
    networks:
      - asgard_net

  heimdall:
    image: heimdall
    container_name: heimdall
    build:
      context: ./heimdall
    command: ["-v", "start", "--optimized", "--spi-theme-cache-themes=false", "--import-realm"]
    restart: always
    env_file:
      - ./.env/heimdall.env
    # ports:
    #   - 8080:8080
    #   - 9000:9000
    #   - 7600-7800:7600-7800
    #   - 57600-57800:57600-57800
    networks:
      - asgard_pub
      - asgard_net
    depends_on:
      - postgres-db
    volumes:
      - ./.conf/heimdall/asgard-realm.json:/opt/keycloak/data/import/asgard-realm.json
  
  bifrost:
    image: bifrost
    container_name: bifrost
    build:
      context: ./bifrost
    restart: always
    env_file:
      - ./.env/bifrost.env
    networks:
      - asgard_pub
    volumes:
      - ./.conf/bifrost/config.yml:/kong/declarative/kong.yml
    ports:
      - 8000:8000
      # - 8443:8443
      # - 8444:8444
      # - 8001-8005:8001-8005
    

  odin:
    image: odin
    container_name: odin
    command: ["--reload", "--root-path", "/api/v1"]
    build:
      context: ./odin
    restart: always
    env_file:
      - ./.env/odin.env
    networks:
      - asgard_pub
      - asgard_net
    depends_on:
      - heimdall
    volumes:
      - ./odin:/app
    # ports:
    #   - 80:80

  loki:
    image: loki
    container_name: loki
    build:
      context: ./loki
    restart: always
    env_file:
      - ./.env/loki.env
    network_mode: "host"
    ports:
      - 6274:6274
      - 6277:6277

volumes:
  postgres_db_data: {}


networks:
  default:
    driver: bridge
  asgard_pub:
    # open network access, please use only when necessary
    internal: false
  asgard_net:
    # private, inter-system channel
    internal: true
