version: "3.7"

services:

  postgres-db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    env_file:
      - ./.env/postgres-db.env
    volumes:
      - asgard_postgres_db_data:/var/lib/postgresql/data
      - ./.conf/postgres-db/create-initial-databases.sh:/docker-entrypoint-initdb.d/create-initial-databases.sh
    network_mode: "host"
    ports:
      - 5432:5432

  heimdall:
    image: heimdall
    container_name: heimdall
    build:
      context: ./heimdall
    command: ["-v", "start", "--optimized", "--spi-theme-cache-themes=false", "--import-realm"]
    restart: always
    env_file:
      - ./.env/heimdall.env
    ports:
      - 8080:8080
      # - 9000:9000
      # - 7600-7800:7600-7800
      # - 57600-57800:57600-57800
    network_mode: "host"
    depends_on:
      - postgres-db
    volumes:
      - ./.conf/heimdall/asgard-realm.json:/opt/keycloak/data/import/asgard-realm.json
  
  bifrost:
    image: bifrost
    container_name: bifrost
    build:
      context: ./bifrost
    restart: always
    env_file:
      - ./.env/bifrost.env
    network_mode: "host"
    volumes:
      - ./.conf/bifrost/config.yml:/kong/declarative/kong.yml
    ports:
      - 8000:8000
      # - 8443:8443
      # - 8444:8444
      # - 8001-8005:8001-8005

  hermod:
    image: hermod
    container_name: hermod
    build:
      context: ./hermod
    restart: always
    network_mode: "host"
    env_file:
      - ./.env/hermod.env
    volumes:
      - ./.conf/hermod:/etc/pushpin
    ports:
      - 7999:7999
      - 5562:5562
    
  loki:
    image: loki
    container_name: loki
    build:
      context: ./loki
    restart: always
    env_file:
      - ./.env/loki.env
    network_mode: "host"
    ports:
      - 6274:6274
      - 6277:6277

  redis:
    image: redis:7
    container_name: redis
    network_mode: "host"
    ports:
      - 6379:6379  

volumes:
  asgard_postgres_db_data: {}



